CREATE TABLE "base_class" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "base_class_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(12) NOT NULL,
	"step_id" integer NOT NULL,
	"sector_id" integer NOT NULL,
	"creation_date" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "discipline" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discipline_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	"annual_workload" integer NOT NULL,
	"base_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sectors" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sectors_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"email" varchar(100) NOT NULL,
	"cnpj" varchar(14),
	"phone1" varchar(20) NOT NULL,
	"phone2" varchar(20),
	"street" varchar(150),
	"number" varchar(10),
	"city" varchar(100),
	"state" varchar(2),
	"zip_code" varchar(15),
	"country" varchar(50) DEFAULT 'Brasil',
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "step" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "step_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sort_order" integer NOT NULL,
	"name" varchar(50) NOT NULL,
	"modality_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "modalities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "modalities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(20) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(100) NOT NULL,
	"email" varchar(100) NOT NULL,
	"senha" varchar(255) NOT NULL,
	"telefone" varchar(20),
	"school_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
