CREATE TYPE "public"."shifts" AS ENUM('day', 'afternoom', 'night');--> statement-breakpoint
CREATE TYPE "public"."status_contract" AS ENUM('active', 'unactive');--> statement-breakpoint
CREATE TABLE "school_periods" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "school_periods_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"year" integer NOT NULL,
	"start_date" timestamp NOT NULL,
	"end_date" timestamp NOT NULL,
	"school_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "base_classes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "base_classes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(12) NOT NULL,
	"step_id" integer NOT NULL,
	"institution_unit_id" integer NOT NULL,
	"creation_date" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "base_class_discipline" (
	"discipline_id" integer NOT NULL,
	"base_id" integer NOT NULL,
	"code" varchar(10) NOT NULL,
	"annual_workload" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "occupations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "occupations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"can_teach" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "contracts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contracts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"employee_id" integer NOT NULL,
	"occupation_id" integer NOT NULL,
	"institution_unit_id" integer NOT NULL,
	"registration_number" varchar(50),
	"start_date" date NOT NULL,
	"end_date" date,
	"status" "status_contract" DEFAULT 'unactive',
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "disciplines" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "disciplines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	"slug" varchar(50) NOT NULL,
	"unit_id" integer,
	CONSTRAINT "school_id_slug_unique_idx" UNIQUE("unit_id","slug")
);
--> statement-breakpoint
CREATE TABLE "employees" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "employees_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cpf" varchar(11) NOT NULL,
	"email" varchar(100) NOT NULL,
	"user_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "employees_cpf_unique" UNIQUE("cpf")
);
--> statement-breakpoint
CREATE TABLE "institutions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "institutions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"email" varchar(100) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "steps" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "steps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sort_order" integer NOT NULL,
	"name" varchar(50) NOT NULL,
	"modality_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "modalities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "modalities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(20) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "classes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "classes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"institution_unit_id" integer NOT NULL,
	"modality_id" integer NOT NULL,
	"step_id" integer NOT NULL,
	"school_period_id" integer NOT NULL,
	"base_class_id" integer NOT NULL,
	"letter" varchar(1) NOT NULL,
	"shift" "shifts" NOT NULL,
	"students_limit" integer DEFAULT 40 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "institution_unit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "institution_unit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cnpj" varchar(14) NOT NULL,
	"phone1" varchar(20) NOT NULL,
	"phone2" varchar(20),
	"street" varchar(150),
	"number" varchar(10),
	"city" varchar(100),
	"state" varchar(2),
	"zip_code" varchar(15),
	"country" varchar(50) DEFAULT 'Brasil',
	"is_head_quarter" boolean NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"institution_id" integer NOT NULL,
	CONSTRAINT "institution_unit_cnpj_unique" UNIQUE("cnpj")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"email" varchar(100) NOT NULL,
	"password" varchar(255) NOT NULL,
	"phone" varchar(20),
	"school_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"is_admin" boolean DEFAULT false NOT NULL,
	"is_root" boolean DEFAULT false NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "school_periods" ADD CONSTRAINT "school_periods_school_id_institutions_id_fk" FOREIGN KEY ("school_id") REFERENCES "public"."institutions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "base_classes" ADD CONSTRAINT "base_classes_institution_unit_id_institutions_id_fk" FOREIGN KEY ("institution_unit_id") REFERENCES "public"."institutions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "base_class_discipline" ADD CONSTRAINT "base_class_discipline_discipline_id_disciplines_id_fk" FOREIGN KEY ("discipline_id") REFERENCES "public"."disciplines"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "base_class_discipline" ADD CONSTRAINT "base_class_discipline_base_id_base_classes_id_fk" FOREIGN KEY ("base_id") REFERENCES "public"."base_classes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_employee_id_employees_id_fk" FOREIGN KEY ("employee_id") REFERENCES "public"."employees"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_occupation_id_occupations_id_fk" FOREIGN KEY ("occupation_id") REFERENCES "public"."occupations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_institution_unit_id_institution_unit_id_fk" FOREIGN KEY ("institution_unit_id") REFERENCES "public"."institution_unit"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "disciplines" ADD CONSTRAINT "disciplines_unit_id_institution_unit_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."institution_unit"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "employees" ADD CONSTRAINT "employees_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "steps" ADD CONSTRAINT "steps_modality_id_modalities_id_fk" FOREIGN KEY ("modality_id") REFERENCES "public"."modalities"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "classes" ADD CONSTRAINT "classes_institution_unit_id_institution_unit_id_fk" FOREIGN KEY ("institution_unit_id") REFERENCES "public"."institution_unit"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "classes" ADD CONSTRAINT "classes_modality_id_modalities_id_fk" FOREIGN KEY ("modality_id") REFERENCES "public"."modalities"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "classes" ADD CONSTRAINT "classes_step_id_steps_id_fk" FOREIGN KEY ("step_id") REFERENCES "public"."steps"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "classes" ADD CONSTRAINT "classes_school_period_id_school_periods_id_fk" FOREIGN KEY ("school_period_id") REFERENCES "public"."school_periods"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "classes" ADD CONSTRAINT "classes_base_class_id_base_classes_id_fk" FOREIGN KEY ("base_class_id") REFERENCES "public"."base_classes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "institution_unit" ADD CONSTRAINT "institution_unit_institution_id_institutions_id_fk" FOREIGN KEY ("institution_id") REFERENCES "public"."institutions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_school_id_institutions_id_fk" FOREIGN KEY ("school_id") REFERENCES "public"."institutions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "contracts_employee_id_idx" ON "contracts" USING btree ("employee_id");--> statement-breakpoint
CREATE INDEX "institution_unit_id_employee_id_idx" ON "contracts" USING btree ("institution_unit_id","employee_id");--> statement-breakpoint
CREATE INDEX "occupation_id_idx" ON "contracts" USING btree ("occupation_id");--> statement-breakpoint
CREATE INDEX "employees_user_id_idx" ON "employees" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "employees_cpf_idx" ON "employees" USING btree ("cpf");