-- Core Institution Tables Migration
-- Creates the foundation tables for managing institutions and their units

CREATE TABLE "institutions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "institutions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"email" varchar(100) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE "institution_unit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "institution_unit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cnpj" varchar(14) NOT NULL,
	"phone1" varchar(20) NOT NULL,
	"phone2" varchar(20),
	"street" varchar(150),
	"number" varchar(10),
	"city" varchar(100),
	"state" varchar(2),
	"zip_code" varchar(15),
	"country" varchar(50) DEFAULT 'Brasil',
	"is_head_quarter" boolean NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"institution_id" integer NOT NULL,
	CONSTRAINT "institution_unit_cnpj_unique" UNIQUE("cnpj")
);
--> statement-breakpoint

ALTER TABLE "institution_unit" ADD CONSTRAINT "institution_unit_institution_id_institutions_id_fk" FOREIGN KEY ("institution_id") REFERENCES "public"."institutions"("id") ON DELETE no action ON UPDATE no action;
