CREATE TYPE "public"."status_contract" AS ENUM('active', 'unactive');--> statement-breakpoint
CREATE TABLE "occupations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "occupations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"can_teach" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "contracts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contracts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"occupation_id" integer NOT NULL,
	"institution_unit_id" integer NOT NULL,
	"registration_number" varchar(50),
	"start_date" date NOT NULL,
	"end_date" date,
	"status" "status_contract" DEFAULT 'unactive',
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_occupation_id_occupations_id_fk" FOREIGN KEY ("occupation_id") REFERENCES "public"."occupations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_institution_unit_id_institution_unit_id_fk" FOREIGN KEY ("institution_unit_id") REFERENCES "public"."institution_unit"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "institution_unit_id_user_id_idx" ON "contracts" USING btree ("institution_unit_id","user_id");--> statement-breakpoint
CREATE INDEX "user_id_idx" ON "contracts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "occupation_id_idx" ON "contracts" USING btree ("occupation_id");