CREATE TABLE "documents" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "documents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"url" varchar(255),
	"content" varchar,
	"status" varchar
);
--> statement-breakpoint
CREATE TABLE "students" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "students_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer,
	"cpf" varchar(11) NOT NULL,
	"name" varchar(100) NOT NULL,
	"birth_date" date NOT NULL
);
--> statement-breakpoint
CREATE TABLE "matriculations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "matriculations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"unit_id" integer NOT NULL,
	"student_id" integer NOT NULL,
	"school_period_id" integer NOT NULL,
	"status" varchar NOT NULL,
	"created_date" date NOT NULL,
	"proof_of_residence_id" integer NOT NULL,
	"scholar_history_id" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "contract_professor_discipline" DROP CONSTRAINT "contract_professor_discipline_unique_idx";--> statement-breakpoint
ALTER TABLE "contracts" ADD COLUMN "salary" numeric(10, 2) NOT NULL;--> statement-breakpoint
ALTER TABLE "students" ADD CONSTRAINT "students_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matriculations" ADD CONSTRAINT "matriculations_unit_id_institution_unit_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."institution_unit"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matriculations" ADD CONSTRAINT "matriculations_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matriculations" ADD CONSTRAINT "matriculations_school_period_id_school_periods_id_fk" FOREIGN KEY ("school_period_id") REFERENCES "public"."school_periods"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matriculations" ADD CONSTRAINT "matriculations_proof_of_residence_id_documents_id_fk" FOREIGN KEY ("proof_of_residence_id") REFERENCES "public"."documents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matriculations" ADD CONSTRAINT "matriculations_scholar_history_id_documents_id_fk" FOREIGN KEY ("scholar_history_id") REFERENCES "public"."documents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contract_professor_discipline" ADD CONSTRAINT "contract_professor_discipline_unique_idx" UNIQUE("contract_id","discipline_id","etapa_id");