-- Curriculum Migration
-- Creates tables for disciplines (subjects), base curricular classes, and their relationships

CREATE TABLE "disciplines" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "disciplines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	"slug" varchar(50) NOT NULL,
	"unit_id" integer,
	CONSTRAINT "school_id_slug_unique_idx" UNIQUE("unit_id","slug")
);
--> statement-breakpoint

CREATE TABLE "base_classes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "base_classes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(12) NOT NULL,
	"step_id" integer NOT NULL,
	"institution_unit_id" integer NOT NULL,
	"creation_date" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE "base_class_discipline" (
	"discipline_id" integer NOT NULL,
	"base_id" integer NOT NULL,
	"code" varchar(10) NOT NULL,
	"annual_workload" integer NOT NULL
);
--> statement-breakpoint

ALTER TABLE "disciplines" ADD CONSTRAINT "disciplines_unit_id_institution_unit_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."institution_unit"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint

ALTER TABLE "base_classes" ADD CONSTRAINT "base_classes_institution_unit_id_institutions_id_fk" FOREIGN KEY ("institution_unit_id") REFERENCES "public"."institutions"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint

ALTER TABLE "base_class_discipline" ADD CONSTRAINT "base_class_discipline_discipline_id_disciplines_id_fk" FOREIGN KEY ("discipline_id") REFERENCES "public"."disciplines"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint

ALTER TABLE "base_class_discipline" ADD CONSTRAINT "base_class_discipline_base_id_base_classes_id_fk" FOREIGN KEY ("base_id") REFERENCES "public"."base_classes"("id") ON DELETE no action ON UPDATE no action;
