-- Academic Operations Migration
-- Creates tables for school periods (school years) and classes (turmas)

CREATE TYPE "public"."shifts" AS ENUM('day', 'afternoom', 'night');
--> statement-breakpoint

CREATE TABLE "school_periods" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "school_periods_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"year" integer NOT NULL,
	"start_date" timestamp NOT NULL,
	"end_date" timestamp NOT NULL,
	"school_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE "classes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "classes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"institution_unit_id" integer NOT NULL,
	"modality_id" integer NOT NULL,
	"step_id" integer NOT NULL,
	"school_period_id" integer NOT NULL,
	"base_class_id" integer NOT NULL,
	"letter" varchar(1) NOT NULL,
	"shift" "shifts" NOT NULL,
	"students_limit" integer DEFAULT 40 NOT NULL
);
--> statement-breakpoint

ALTER TABLE "school_periods" ADD CONSTRAINT "school_periods_school_id_institutions_id_fk" FOREIGN KEY ("school_id") REFERENCES "public"."institutions"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint

ALTER TABLE "classes" ADD CONSTRAINT "classes_institution_unit_id_institution_unit_id_fk" FOREIGN KEY ("institution_unit_id") REFERENCES "public"."institution_unit"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint

ALTER TABLE "classes" ADD CONSTRAINT "classes_modality_id_modalities_id_fk" FOREIGN KEY ("modality_id") REFERENCES "public"."modalities"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint

ALTER TABLE "classes" ADD CONSTRAINT "classes_step_id_steps_id_fk" FOREIGN KEY ("step_id") REFERENCES "public"."steps"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint

ALTER TABLE "classes" ADD CONSTRAINT "classes_school_period_id_school_periods_id_fk" FOREIGN KEY ("school_period_id") REFERENCES "public"."school_periods"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint

ALTER TABLE "classes" ADD CONSTRAINT "classes_base_class_id_base_classes_id_fk" FOREIGN KEY ("base_class_id") REFERENCES "public"."base_classes"("id") ON DELETE no action ON UPDATE no action;
