-- Students and Responsibles
CREATE TABLE "students" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "students_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer,
	"cpf" varchar(11) NOT NULL,
	"name" varchar(100) NOT NULL,
	"birth_date" date NOT NULL,
	"sex" sex_enum NOT NULL
);

CREATE TABLE "responsibles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "responsibles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"cpf" varchar(11) NOT NULL,
	"email" varchar(100) NOT NULL,
	"birth_date" date NOT NULL,
	"phone" varchar(11) NOT NULL,
	"user_id" integer,
	CONSTRAINT "responsibles_cpf_unique" UNIQUE("cpf"),
	CONSTRAINT "responsibles_email_unique" UNIQUE("email"),
	CONSTRAINT "responsibles_userId_unique" UNIQUE("user_id")
);

ALTER TABLE "students" ADD CONSTRAINT "students_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "responsibles" ADD CONSTRAINT "responsibles_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;

-- DOWN
ALTER TABLE "responsibles" DROP CONSTRAINT IF EXISTS "responsibles_user_id_users_id_fk";
ALTER TABLE "students" DROP CONSTRAINT IF EXISTS "students_user_id_users_id_fk";
DROP TABLE IF EXISTS "responsibles";
DROP TABLE IF EXISTS "students";
