-- Persons Table (Centralized Personal Information)
CREATE TABLE "persons" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "persons_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"cpf" varchar(11) NOT NULL,
	"email" varchar(100),
	"phone" varchar(11),
	"gender" "gender_enum",
	"birth_date" date NOT NULL,
	"school_id" integer NOT NULL,
	CONSTRAINT "persons_cpf_unique" UNIQUE("cpf"),
	CONSTRAINT "persons_email_unique" UNIQUE("email"),
	CONSTRAINT "persons_table_unique_idx" UNIQUE("cpf","school_id")
);

ALTER TABLE "persons" ADD CONSTRAINT "persons_school_id_institutions_id_fk" FOREIGN KEY ("school_id") REFERENCES "public"."institutions"("id") ON DELETE no action ON UPDATE no action;

-- DOWN
ALTER TABLE "persons" DROP CONSTRAINT IF EXISTS "persons_school_id_institutions_id_fk";
DROP TABLE IF EXISTS "persons";
