-- Students and Responsibles
CREATE TABLE "students" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "students_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"person_id" integer NOT NULL,
	"user_id" integer,
	CONSTRAINT "students_personId_unique" UNIQUE("person_id"),
	CONSTRAINT "students_userId_unique" UNIQUE("user_id")
);

ALTER TABLE "students" ADD CONSTRAINT "students_person_id_persons_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "students" ADD CONSTRAINT "students_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;

-- DOWN
ALTER TABLE "students" DROP CONSTRAINT IF EXISTS "students_user_id_users_id_fk";
ALTER TABLE "students" DROP CONSTRAINT IF EXISTS "students_person_id_persons_id_fk";
DROP TABLE IF EXISTS "students";
