-- Classes
CREATE TABLE "classes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "classes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"institution_unit_id" integer NOT NULL,
	"modality_id" integer NOT NULL,
	"step_id" integer NOT NULL,
	"school_period_id" integer NOT NULL,
	"base_class_id" integer NOT NULL,
	"letter" varchar(1) NOT NULL,
	"shift" "shifts" NOT NULL,
	"students_limit" integer DEFAULT 40 NOT NULL
);

ALTER TABLE "classes" ADD CONSTRAINT "classes_institution_unit_id_institution_unit_id_fk" FOREIGN KEY ("institution_unit_id") REFERENCES "public"."institution_unit"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "classes" ADD CONSTRAINT "classes_modality_id_modalities_id_fk" FOREIGN KEY ("modality_id") REFERENCES "public"."modalities"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "classes" ADD CONSTRAINT "classes_step_id_steps_id_fk" FOREIGN KEY ("step_id") REFERENCES "public"."steps"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "classes" ADD CONSTRAINT "classes_school_period_id_school_periods_id_fk" FOREIGN KEY ("school_period_id") REFERENCES "public"."school_periods"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "classes" ADD CONSTRAINT "classes_base_class_id_base_classes_id_fk" FOREIGN KEY ("base_class_id") REFERENCES "public"."base_classes"("id") ON DELETE no action ON UPDATE no action;

-- DOWN
ALTER TABLE "classes" DROP CONSTRAINT IF EXISTS "classes_base_class_id_base_classes_id_fk";
ALTER TABLE "classes" DROP CONSTRAINT IF EXISTS "classes_school_period_id_school_periods_id_fk";
ALTER TABLE "classes" DROP CONSTRAINT IF EXISTS "classes_step_id_steps_id_fk";
ALTER TABLE "classes" DROP CONSTRAINT IF EXISTS "classes_modality_id_modalities_id_fk";
ALTER TABLE "classes" DROP CONSTRAINT IF EXISTS "classes_institution_unit_id_institution_unit_id_fk";
DROP TABLE IF EXISTS "classes";
