-- Users
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"login" varchar(100) NOT NULL,
	"password" varchar(255) NOT NULL,
	"school_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"is_admin" boolean DEFAULT false NOT NULL,
	"is_root" boolean DEFAULT false NOT NULL,
	CONSTRAINT "users_login_unique" UNIQUE("login")
);

ALTER TABLE "users" ADD CONSTRAINT "users_school_id_institutions_id_fk" FOREIGN KEY ("school_id") REFERENCES "public"."institutions"("id") ON DELETE no action ON UPDATE no action;

-- DOWN
ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_school_id_institutions_id_fk";
DROP TABLE IF EXISTS "users";
