-- Documents
CREATE TABLE "documents" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "documents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"url" varchar(255),
	"content" varchar,
	"status" varchar
);

-- DOWN
DROP TABLE IF EXISTS "documents";
