-- Matriculations and Matriculation Requests
CREATE TABLE "matriculations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "matriculations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"unit_id" integer NOT NULL,
	"student_id" integer NOT NULL,
	"school_period_id" integer NOT NULL,
	"status" varchar NOT NULL,
	"created_date" date NOT NULL,
	"proof_of_residence_id" integer NOT NULL,
	"scholar_history_id" integer NOT NULL
);

CREATE TABLE "responsibility_relations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "responsibility_relations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(20) NOT NULL,
	"slug" varchar(20) NOT NULL,
	CONSTRAINT "responsibility_relations_unique" UNIQUE("slug")
);

CREATE TABLE "matriculation_request_statuses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "matriculation_request_statuses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(25) NOT NULL,
	"slug" varchar(25) NOT NULL
);

CREATE TABLE "matriculation_requests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "matriculation_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"unit_id" integer NOT NULL,
	"student_id" integer NOT NULL,
	"responsible_id" integer NOT NULL,
	"school_period_id" integer NOT NULL,
	"step_id" integer NOT NULL,
	"responsibility_relation_id" integer NOT NULL,
	"status_id" integer NOT NULL,
	"created_date" date NOT NULL,
	"proof_of_residence_id" integer NOT NULL,
	"scholar_history_id" integer NOT NULL,
	"student_document_id" integer NOT NULL,
	"responsible_document_id" integer NOT NULL,
	"observations" varchar(255)
);

ALTER TABLE "matriculations" ADD CONSTRAINT "matriculations_unit_id_institution_unit_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."institution_unit"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "matriculations" ADD CONSTRAINT "matriculations_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "matriculations" ADD CONSTRAINT "matriculations_school_period_id_school_periods_id_fk" FOREIGN KEY ("school_period_id") REFERENCES "public"."school_periods"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "matriculations" ADD CONSTRAINT "matriculations_proof_of_residence_id_documents_id_fk" FOREIGN KEY ("proof_of_residence_id") REFERENCES "public"."documents"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "matriculations" ADD CONSTRAINT "matriculations_scholar_history_id_documents_id_fk" FOREIGN KEY ("scholar_history_id") REFERENCES "public"."documents"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "matriculation_requests" ADD CONSTRAINT "matriculation_requests_unit_id_institution_unit_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."institution_unit"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "matriculation_requests" ADD CONSTRAINT "matriculation_requests_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "matriculation_requests" ADD CONSTRAINT "matriculation_requests_responsible_id_persons_id_fk" FOREIGN KEY ("responsible_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "matriculation_requests" ADD CONSTRAINT "matriculation_requests_school_period_id_school_periods_id_fk" FOREIGN KEY ("school_period_id") REFERENCES "public"."school_periods"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "matriculation_requests" ADD CONSTRAINT "matriculation_requests_proof_of_residence_id_documents_id_fk" FOREIGN KEY ("proof_of_residence_id") REFERENCES "public"."documents"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "matriculation_requests" ADD CONSTRAINT "matriculation_requests_scholar_history_id_documents_id_fk" FOREIGN KEY ("scholar_history_id") REFERENCES "public"."documents"("id") ON DELETE no action ON UPDATE no action;

ALTER TABLE "matriculation_requests" ADD CONSTRAINT "matriculation_requests_step_id_steps_id_fk" FOREIGN KEY ("step_id") REFERENCES "public"."steps"("id") ON DELETE no action ON UPDATE no action;

ALTER TABLE "matriculation_requests" ADD CONSTRAINT "matriculation_requests_responsibility_relation_id_responsibility_relations_id_fk" FOREIGN KEY ("responsibility_relation_id") REFERENCES "public"."responsibility_relations"("id") ON DELETE no action ON UPDATE no action;

ALTER TABLE "matriculation_requests" ADD CONSTRAINT "matriculation_requests_student_document_id_documents_id_fk" FOREIGN KEY ("student_document_id") REFERENCES "public"."documents"("id") ON DELETE no action ON UPDATE no action;

ALTER TABLE "matriculation_requests" ADD CONSTRAINT "matriculation_requests_responsible_document_id_documents_id_fk" FOREIGN KEY ("responsible_document_id") REFERENCES "public"."documents"("id") ON DELETE no action ON UPDATE no action;

ALTER TABLE "matriculation_requests" ADD CONSTRAINT "matriculation_requests_status_id_matriculation_request_statuses_id_fk" FOREIGN KEY ("status_id") REFERENCES "public"."matriculation_request_statuses"("id") ON DELETE no action ON UPDATE no action;

-- DOWN
ALTER TABLE "matriculation_requests" DROP CONSTRAINT IF EXISTS "matriculation_requests_status_id_matriculation_request_statuses_id_fk";
ALTER TABLE "matriculation_requests" DROP CONSTRAINT IF EXISTS "matriculation_requests_responsible_document_id_documents_id_fk";
ALTER TABLE "matriculation_requests" DROP CONSTRAINT IF EXISTS "matriculation_requests_student_document_id_documents_id_fk";
ALTER TABLE "matriculation_requests" DROP CONSTRAINT IF EXISTS "matriculation_requests_responsibility_relation_id_responsibility_relations_id_fk";
ALTER TABLE "matriculation_requests" DROP CONSTRAINT IF EXISTS "matriculation_requests_step_id_steps_id_fk";
ALTER TABLE "matriculation_requests" DROP CONSTRAINT IF EXISTS "matriculation_requests_scholar_history_id_documents_id_fk";
ALTER TABLE "matriculation_requests" DROP CONSTRAINT IF EXISTS "matriculation_requests_proof_of_residence_id_documents_id_fk";
ALTER TABLE "matriculation_requests" DROP CONSTRAINT IF EXISTS "matriculation_requests_school_period_id_school_periods_id_fk";
ALTER TABLE "matriculation_requests" DROP CONSTRAINT IF EXISTS "matriculation_requests_responsible_id_persons_id_fk";
ALTER TABLE "matriculation_requests" DROP CONSTRAINT IF EXISTS "matriculation_requests_student_id_students_id_fk";
ALTER TABLE "matriculation_requests" DROP CONSTRAINT IF EXISTS "matriculation_requests_unit_id_institution_unit_id_fk";
ALTER TABLE "matriculations" DROP CONSTRAINT IF EXISTS "matriculations_scholar_history_id_documents_id_fk";
ALTER TABLE "matriculations" DROP CONSTRAINT IF EXISTS "matriculations_proof_of_residence_id_documents_id_fk";
ALTER TABLE "matriculations" DROP CONSTRAINT IF EXISTS "matriculations_school_period_id_school_periods_id_fk";
ALTER TABLE "matriculations" DROP CONSTRAINT IF EXISTS "matriculations_student_id_students_id_fk";
ALTER TABLE "matriculations" DROP CONSTRAINT IF EXISTS "matriculations_unit_id_institution_unit_id_fk";
DROP TABLE IF EXISTS "matriculation_requests";
DROP TABLE IF EXISTS "matriculation_request_statuses";
DROP TABLE IF EXISTS "responsibility_relations";
DROP TABLE IF EXISTS "matriculations";
