-- Occupations, Employees and Contracts
CREATE TABLE "occupations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "occupations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"can_teach" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now()
);

CREATE TABLE "employees" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "employees_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE "contracts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contracts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"employee_id" integer NOT NULL,
	"occupation_id" integer NOT NULL,
	"institution_unit_id" integer NOT NULL,
	"registration_number" varchar(50),
	"start_date" date NOT NULL,
	"end_date" date,
	"status" "status_contract" DEFAULT 'unactive',
	"salary" numeric(10, 2) NOT NULL,
	"created_at" timestamp DEFAULT now()
);

CREATE TABLE "contract_professor_discipline" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contract_professor_discipline_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contract_id" integer NOT NULL,
	"discipline_id" integer NOT NULL,
	"etapa_id" integer NOT NULL,
	CONSTRAINT "contract_professor_discipline_unique_idx" UNIQUE("contract_id","discipline_id","etapa_id")
);

ALTER TABLE "employees" ADD CONSTRAINT "employees_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_employee_id_employees_id_fk" FOREIGN KEY ("employee_id") REFERENCES "public"."employees"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_occupation_id_occupations_id_fk" FOREIGN KEY ("occupation_id") REFERENCES "public"."occupations"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_institution_unit_id_institution_unit_id_fk" FOREIGN KEY ("institution_unit_id") REFERENCES "public"."institution_unit"("id") ON DELETE no action ON UPDATE no action;

CREATE INDEX "contracts_employee_id_idx" ON "contracts" USING btree ("employee_id");
CREATE INDEX "institution_unit_id_employee_id_idx" ON "contracts" USING btree ("institution_unit_id","employee_id");
CREATE INDEX "occupation_id_idx" ON "contracts" USING btree ("occupation_id");

-- DOWN
DROP INDEX IF EXISTS "occupation_id_idx";
DROP INDEX IF EXISTS "institution_unit_id_employee_id_idx";
DROP INDEX IF EXISTS "contracts_employee_id_idx";
ALTER TABLE "contracts" DROP CONSTRAINT IF EXISTS "contracts_institution_unit_id_institution_unit_id_fk";
ALTER TABLE "contracts" DROP CONSTRAINT IF EXISTS "contracts_occupation_id_occupations_id_fk";
ALTER TABLE "contracts" DROP CONSTRAINT IF EXISTS "contracts_employee_id_employees_id_fk";
ALTER TABLE "employees" DROP CONSTRAINT IF EXISTS "employees_user_id_users_id_fk";
DROP TABLE IF EXISTS "contract_professor_discipline";
DROP TABLE IF EXISTS "contracts";
DROP TABLE IF EXISTS "employees";
DROP TABLE IF EXISTS "occupations";
