-- Migration: Educational Structure
-- Description: Creates modalities and educational steps
-- Created: 2025-12-23T10:01:00

-- UP
CREATE TABLE "modalities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "modalities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(20) NOT NULL
);

CREATE TABLE "steps" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "steps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sort_order" integer NOT NULL,
	"name" varchar(50) NOT NULL,
	"modality_id" integer NOT NULL
);

ALTER TABLE "steps" ADD CONSTRAINT "steps_modality_id_modalities_id_fk" FOREIGN KEY ("modality_id") REFERENCES "public"."modalities"("id") ON DELETE no action ON UPDATE no action;

-- DOWN
DROP TABLE IF EXISTS "steps" CASCADE;
DROP TABLE IF EXISTS "modalities" CASCADE;
