CREATE TYPE "public"."status_contract" AS ENUM('active', 'unactive');
CREATE TABLE "occupations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "occupations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"can_teach" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now()
);

CREATE TABLE "employees" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "cpf" varchar(11) NOT NULL UNIQUE,
  "email" varchar(100) NOT NULL,
  "user_id" integer NOT NULL REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX "employees_user_id_idx" ON "employees" ("user_id");
CREATE INDEX "employees_cpf_idx" ON "employees" ("cpf");

CREATE TABLE "contracts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contracts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"employee_id" integer NOT NULL,
	"occupation_id" integer NOT NULL,
	"institution_unit_id" integer NOT NULL,
	"registration_number" varchar(50),
	"start_date" date NOT NULL,
	"end_date" date,
	"status" "status_contract" DEFAULT 'unactive',
	"created_at" timestamp DEFAULT now()
);

ALTER TABLE "contracts" ADD CONSTRAINT "contracts_employee_id_employees_id_fk" FOREIGN KEY ("employee_id") REFERENCES "public"."employees"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_occupation_id_occupations_id_fk" FOREIGN KEY ("occupation_id") REFERENCES "public"."occupations"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_institution_unit_id_institution_unit_id_fk" FOREIGN KEY ("institution_unit_id") REFERENCES "public"."institution_unit"("id") ON DELETE no action ON UPDATE no action;
CREATE INDEX "contracts_employee_id_idx" ON "contracts" USING btree ("employee_id");
CREATE INDEX "institution_unit_id_employee_id_idx" ON "contracts" USING btree ("institution_unit_id","employee_id");
CREATE INDEX "occupation_id_idx" ON "contracts" USING btree ("occupation_id");

-- DOWN
-- Drop tables in reverse order to handle foreign key constraints
DROP TABLE IF EXISTS "contracts";
DROP TABLE IF EXISTS "employees";
DROP TABLE IF EXISTS "occupations";

-- Drop custom types
DROP TYPE IF EXISTS "public"."status_contract";
