-- School Periods and Modalities
CREATE TABLE "school_periods" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "school_periods_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"year" integer NOT NULL,
	"start_date" timestamp NOT NULL,
	"end_date" timestamp NOT NULL,
	"school_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE "modalities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "modalities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(20) NOT NULL
);

CREATE TABLE "steps" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "steps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sort_order" integer NOT NULL,
	"name" varchar(50) NOT NULL,
	"modality_id" integer NOT NULL
);

ALTER TABLE "school_periods" ADD CONSTRAINT "school_periods_school_id_institutions_id_fk" FOREIGN KEY ("school_id") REFERENCES "public"."institutions"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "steps" ADD CONSTRAINT "steps_modality_id_modalities_id_fk" FOREIGN KEY ("modality_id") REFERENCES "public"."modalities"("id") ON DELETE no action ON UPDATE no action;

-- DOWN
ALTER TABLE "steps" DROP CONSTRAINT IF EXISTS "steps_modality_id_modalities_id_fk";
ALTER TABLE "school_periods" DROP CONSTRAINT IF EXISTS "school_periods_school_id_institutions_id_fk";
DROP TABLE IF EXISTS "steps";
DROP TABLE IF EXISTS "modalities";
DROP TABLE IF EXISTS "school_periods";
